# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.3.2
_src_path: gh:LCOGT/k8s-application-copier-template
app_description: Astronomical observing management backend
app_name: obs-portal
build_container_on_every_push: true
default_branch_bypass_branch_protection_rules: false
default_branch_name: main
delete_branches_on_merge: true
dockerfile_path: Dockerfile
have_deploy_repo: false
