#!/bin/bash

# Build and push a docker image. The first positional argument is the image tag, which
# defaults to "latest" if not set.

if [ -z "$DOCKER_USERNAME" ] || [ -z "$DOCKER_PASSWORD" ]; then
  echo "Environment variables DOCKER_USERNAME and DOCKER_PASSWORD must be set"
  exit 1
fi

TAG=${1:-latest}
PROJECT_NAME=observation-portal
IMAGE_NAME="$DOCKER_USERNAME"/"$PROJECT_NAME":"$TAG"

echo "Building $IMAGE_NAME"

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker build -t "$IMAGE_NAME" .
docker push "$IMAGE_NAME"
