#!/bin/bash

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker build -t observatorycontrolsystem/observation-portal .
docker push observatorycontrolsystem/observation-portal
