apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: obs-portal
requires:
  - configs:
    - obs-portal-app-image
manifests:
  kustomize:
    paths:
      - k8s/envs/local/
deploy:
  kubectl: {}
  logs:
    prefix: podAndContainer
---

apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: obs-portal-app-image
build:
  tagPolicy:
    gitCommit:
      variant: Tags
  artifacts:
    - image: observation-portal
      custom:
        buildCommand: skaffold-builder-buildx
        dependencies:
          dockerfile:
            path: Dockerfile
    - image: nginx-mod-zip
      context: nginx-mod-zip/
      custom:
        buildCommand: skaffold-builder-buildx
        dependencies:
          dockerfile:
            path: Dockerfile
---

apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: obs-portal-deps
manifests:
  kustomize:
    paths:
      - k8s/envs/local-deps/
deploy:
  kubectl: {}
  logs:
    prefix: podAndContainer
