apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: app
requires:
  - configs:
    - app-image
manifests:
  kustomize:
    paths:
      - k8s/envs/local/
deploy:
  kubectl: {}
  logs:
    prefix: podAndContainer
---

apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: app-image
build:
  tagPolicy:
    gitCommit:
      variant: Tags
  artifacts:
    - image: observation-portal
      custom:
        buildCommand: skaffold-builder-buildx
        dependencies:
          dockerfile:
            path: Dockerfile
---

apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: deps
manifests:
  kustomize:
    paths:
      - k8s/envs/local-deps/
deploy:
  kubectl: {}
  helm:
    releases:
      - name: postgresql
        remoteChart: oci://registry-1.docker.io/bitnamicharts/postgresql
        version: 12.12.10
        namespace: observation-portal-pg
        createNamespace: true
        setValues:
          architecture: standalone
          primary.persistence.size: 2Gi
          auth:
            database: observationportal
            username: observationportal
            password: observationportal

      - name: redis
        remoteChart: oci://registry-1.docker.io/bitnamicharts/redis
        version: 19.1.0
        namespace: observation-portal-redis
        createNamespace: true
        setValues:
          architecture: standalone
          auth.password: observationportal
          master.persistence.enabled: false
