apiVersion: kpt.dev/v1
kind: RenderHelmChart
metadata: # kpt-merge: /example
  name: redis
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: kpt.dev|RenderHelmChart|default|example
# See https://catalog.kpt.dev/render-helm-chart/v0.2/
helmCharts:
  - chartArgs:
      repo: oci://registry-1.docker.io/bitnamicharts
      name: redis
      version: 19.1.0
    templateOptions:
      apiVersions:
        - 1.26.15
      releaseName: redis
      namespace: obs-portal
      includeCRDs: true
      skipTests: true
      values:
        valuesInline:
          # Chart values go here
          image:
            repository: bitnamilegacy/redis
          architecture: standalone
          auth:
            password: observationportal
          master:
            persistence:
              enabled: false
