# Generated by Django 2.2.23 on 2021-06-18 21:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciapplications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scienceapplication',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
