# Generated by Django 2.2.18 on 2021-06-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciapplications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerequest',
            name='instrument_types',
            field=models.ManyToManyField(related_name='timerequests', to='sciapplications.Instrument'),
        ),
    ]
