# Generated by Django 2.2.23 on 2021-06-24 01:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciapplications', '0002_scienceapplication_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scienceapplication',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, help_text='List of strings tagging this appllication', size=None),
        ),
    ]
