# Generated by Django 2.2.23 on 2021-07-08 16:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciapplications', '0004_remove_timerequest_instrument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timerequest',
            options={'ordering': ('semester',)},
        ),
        migrations.AddField(
            model_name='scienceapplication',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='List of strings tagging this application', size=None),
        ),
    ]
