# Generated by Django 4.0.4 on 2023-04-13 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sciapplications', '0005_auto_20210708_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['code']},
        ),
    ]
