# Generated by Django 4.1.13 on 2024-05-18 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sciapplications', '0006_alter_instrument_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScienceApplicationReviewProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('science_category', models.CharField(choices=[('EXPLOSIVE_TRANSIENTS', 'Explosive Transients'), ('ACTIVE_GALAXIES', 'Active Galaxies'), ('STARS_STELLAR_ACTIVITY', 'Stars and Stellar Activity'), ('SOLAR_SYSTEM_SMALL_BODIES', 'Solar System Small Bodies'), ('MISC', 'Miscellaneous')], default='MISC', max_length=255)),
                ('technical_review', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('UNDER_REVIEW', 'Under Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='UNDER_REVIEW', max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('science_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_process', to='sciapplications.scienceapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ScienceApplicationUserReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, default='')),
                ('completed', models.BooleanField(default=False)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True)),
                ('review_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='sciapplications.scienceapplicationreviewprocess')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sciapplication_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='scienceapplicationuserreview',
            constraint=models.UniqueConstraint(fields=('review_process', 'user'), name='sciapplications_scienceapplicationuserreview_primary_key'),
        ),
        migrations.AddConstraint(
            model_name='scienceapplicationuserreview',
            constraint=models.UniqueConstraint(condition=models.Q(('primary', True)), fields=('review_process',), name='sciapplications_scienceapplicationuserreview_is_primary', violation_error_message='Only one user review can be marked as the primary'),
        ),
    ]
