# Generated by Django 4.1.13 on 2024-10-24 18:30

from django.db import migrations, models
import observation_portal.sciapplications.models


class Migration(migrations.Migration):

    dependencies = [
        ('sciapplications', '0007_reviewpanel_scienceapplicationreview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scienceapplicationreview',
            name='pdf',
            field=models.FileField(blank=True, help_text='Anonymized proposal PDF that will be visible to the panel.', null=True, upload_to=observation_portal.sciapplications.models.review_pdf_upload_path),
        ),
    ]
