# Generated by Django 4.1.13 on 2024-12-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciapplications', '0009_reviewpanel_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scienceapplicationreview',
            name='notify_submitter',
        ),
        migrations.RemoveField(
            model_name='scienceapplicationreview',
            name='notify_submitter_additional_message',
        ),
        migrations.AddField(
            model_name='scienceapplicationreview',
            name='accepted_priority',
            field=models.CharField(choices=[('BOTTOM', 'bottom'), ('MIDDLE', 'middle'), ('TOP', 'top')], default='BOTTOM', help_text='Priority at which the proposal is accpeted', max_length=255),
        ),
        migrations.AddField(
            model_name='scienceapplicationreview',
            name='submitter_notified',
            field=models.DateTimeField(blank=True, help_text='When/if the submitter was notified of the status (most recent)', null=True),
        ),
    ]
