# Generated by Django 4.1.13 on 2025-04-10 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sciapplications', '0010_remove_scienceapplicationreview_notify_submitter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scienceapplicationuserreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
