# Generated by Django 4.1.13 on 2025-04-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciapplications', '0011_scienceapplicationuserreview_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='scienceapplicationreview',
            name='secondary_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
