# Generated by Django 4.2.23 on 2025-10-09 00:42

from django.db import migrations, models
import observation_portal.sciapplications.models


class Migration(migrations.Migration):

    dependencies = [
        ('sciapplications', '0012_scienceapplicationreview_secondary_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='scienceapplication',
            name='pdf_generated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scienceapplication',
            name='pdf_one',
            field=models.FileField(blank=True, null=True, upload_to=observation_portal.sciapplications.models.pdf_one_upload_path),
        ),
        migrations.AddField(
            model_name='scienceapplication',
            name='pdf_two',
            field=models.FileField(blank=True, null=True, upload_to=observation_portal.sciapplications.models.pdf_two_upload_path),
        ),
        migrations.AddField(
            model_name='scienceapplicationreview',
            name='admin_pdf',
            field=models.FileField(blank=True, help_text='PDF that will be visible to admins.', null=True, upload_to=observation_portal.sciapplications.models.review_admin_pdf_upload_path),
        ),
    ]
