# Generated by Django 4.2.23 on 2025-10-28 19:49

from django.db import migrations, models
import observation_portal.sciapplications.models


class Migration(migrations.Migration):

    dependencies = [
        ('sciapplications', '0012_scienceapplicationreview_secondary_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='scienceapplication',
            name='references_pdf',
            field=models.FileField(blank=True, null=True, upload_to=observation_portal.sciapplications.models.references_upload_path),
        ),
        migrations.AddField(
            model_name='scienceapplication',
            name='sci_justification_pdf',
            field=models.FileField(blank=True, null=True, upload_to=observation_portal.sciapplications.models.sci_justification_upload_path),
        ),
        migrations.AddField(
            model_name='scienceapplicationreview',
            name='admin_pdf',
            field=models.FileField(blank=True, help_text='PDF that will be visible to admins.', null=True, upload_to=observation_portal.sciapplications.models.review_admin_pdf_upload_path),
        ),
    ]
