# Generated by Django 4.2.23 on 2025-10-28 20:43

from os.path import basename
from django.db import migrations


def prepend_user_id_to_pdf_files_forwards(apps, schema_editor):
    ScienceApplication = apps.get_model("sciapplications", "ScienceApplication")

    for item in ScienceApplication.objects.all():
        filename = basename(item.pdf.name)
        item.pdf.name = 'sciapps/{0}/{1}/{2}/{3}'.format(item.call.semester.id, item.submitter.id, item.id, filename)
        item.save()

def prepend_user_id_to_pdf_files_backwards(apps, schema_editor):
    ScienceApplication = apps.get_model("sciapplications", "ScienceApplication")

    for item in ScienceApplication.objects.all():
        filename = basename(item.pdf.name)
        item.pdf.name = 'sciapps/{0}/{1}/{2}'.format(item.call.semester.id, item.id, filename)
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('sciapplications', '0013_scienceapplication_references_pdf_and_more'),
    ]

    operations = [
        migrations.RunPython(prepend_user_id_to_pdf_files_forwards, prepend_user_id_to_pdf_files_backwards)
    ]
