# Generated by Django 2.1.7 on 2019-03-19 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('education_user', models.BooleanField(default=False)),
                ('notifications_enabled', models.BooleanField(default=False)),
                ('notifications_on_authored_only', models.BooleanField(default=False)),
                ('simple_interface', models.BooleanField(default=False)),
                ('view_authored_requests_only', models.BooleanField(default=False)),
                ('staff_view', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
