# Generated by Django 4.0.3 on 2022-04-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_terms_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
