# Generated by Django 2.1.7 on 2019-05-14 00:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_auto_20190408_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='events',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='Raw set of telescope events during this observation, in json format'),
        ),
    ]
