# Generated by Django 4.0.3 on 2022-03-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0005_auto_20210116_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='events',
            field=models.JSONField(blank=True, default=list, help_text='Raw set of telescope events during this observation, in json format'),
        ),
    ]
