# Generated by Django 4.0.3 on 2023-01-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0007_alter_configurationstatus_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationstatus',
            name='time_charged',
            field=models.FloatField(blank=True, default=0.0, help_text='Time in fractional hours that was debited from a TimeAllocation for this configuration'),
        ),
    ]
