# Generated by Django 4.1.13 on 2025-01-30 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requestgroups', '0024_alter_requestgroup_observation_type'),
        ('observations', '0008_configurationstatus_time_charged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationstatus',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuration_status', to='requestgroups.configuration'),
        ),
    ]
