# Generated by Django 4.2.23 on 2025-12-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0009_alter_configurationstatus_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationstatus',
            name='state',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ATTEMPTED', 'ATTEMPTED'), ('NOT_ATTEMPTED', 'NOT_ATTEMPTED'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('BAD_DATA', 'BAD_DATA')], default='PENDING', help_text='Current state of this Configuration Status', max_length=40),
        ),
        migrations.AlterField(
            model_name='observation',
            name='state',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('NOT_ATTEMPTED', 'NOT_ATTEMPTED'), ('COMPLETED', 'COMPLETED'), ('CANCELED', 'CANCELED'), ('ABORTED', 'ABORTED'), ('FAILED', 'FAILED'), ('BAD_DATA', 'BAD_DATA')], db_index=True, default='PENDING', help_text='Current State of this Observation', max_length=40),
        ),
    ]
