# Generated by Django 2.1.7 on 2019-03-22 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestgroups', '0002_auto_20190319_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisitionconfig',
            name='exposure_time',
            field=models.FloatField(blank=True, help_text='Acquisition exposure time', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(60.0)]),
        ),
    ]
