# Generated by Django 2.1.7 on 2019-04-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestgroups', '0003_acquisitionconfig_exposure_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidingconfig',
            name='state',
        ),
        migrations.AddField(
            model_name='guidingconfig',
            name='optional',
            field=models.BooleanField(default=True, help_text='Whether the guiding is optional or not'),
        ),
    ]
