# Generated by Django 2.2 on 2019-05-01 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestgroups', '0004_auto_20190410_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrumentconfig',
            old_name='rot_mode',
            new_name='rotator_mode',
        ),
    ]
