# Generated by Django 2.1.7 on 2019-05-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestgroups', '0005_auto_20190501_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='type',
            field=models.CharField(choices=[('EXPOSE', 'EXPOSE'), ('SKY_FLAT', 'SKY_FLAT'), ('STANDARD', 'STANDARD'), ('ARC', 'ARC'), ('LAMP_FLAT', 'LAMP_FLAT'), ('SPECTRUM', 'SPECTRUM'), ('AUTO_FOCUS', 'AUTO_FOCUS'), ('TRIPLE', 'TRIPLE'), ('NRES_TEST', 'NRES_TEST'), ('NRES_SPECTRUM', 'NRES_SPECTRUM'), ('NRES_EXPOSE', 'NRES_EXPOSE'), ('NRES_DARK', 'NRES_DARK'), ('NRES_BIAS', 'NRES_BIAS'), ('ENGINEERING', 'ENGINEERING'), ('SCRIPT', 'SCRIPT'), ('BIAS', 'BIAS'), ('DARK', 'DARK')], help_text='The type of exposures for the observations under this Configuration', max_length=50),
        ),
    ]
