# Generated by Django 2.1.7 on 2019-05-16 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestgroups', '0006_auto_20190514_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidingconfig',
            name='exposure_time',
            field=models.FloatField(default=10.0, help_text='Guiding exposure time', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='instrumentconfig',
            name='exposure_time',
            field=models.FloatField(help_text='Exposure time in seconds. A tool to aid in deciding on an exposure time is located <a href="https://lco.global/files/etc/exposure_time_calculator.html">here</a>.', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
