# Generated by Django 2.1.7 on 2019-05-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestgroups', '0008_auto_20190516_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='coordinate_system',
        ),
        migrations.RemoveField(
            model_name='target',
            name='equinox',
        ),
        migrations.RemoveField(
            model_name='target',
            name='pitch',
        ),
        migrations.RemoveField(
            model_name='target',
            name='roll',
        ),
        migrations.AlterField(
            model_name='target',
            name='type',
            field=models.CharField(choices=[('ICRS', 'ICRS'), ('ORBITAL_ELEMENTS', 'ORBITAL_ELEMENTS'), ('HOUR_ANGLE', 'HOUR_ANGLE'), ('SATELLITE', 'SATELLITE')], help_text='The type of this Target', max_length=255),
        ),
    ]
