# Generated by Django 2.2.2 on 2019-07-02 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestgroups', '0010_auto_20190612_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='eccentricity',
            field=models.FloatField(blank=True, help_text='Eccentricity of the orbit', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
