# Generated by Django 2.2.4 on 2019-11-23 02:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestgroups', '0011_auto_20190702_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='repeat_duration',
            field=models.FloatField(blank=True, help_text='The requested duration for this configuration to be repeated within. Only applicable to REPEAT_* type configurations.', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='configuration duration'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='type',
            field=models.CharField(choices=[('EXPOSE', 'EXPOSE'), ('REPEAT_EXPOSE', 'REPEAT_EXPOSE'), ('SKY_FLAT', 'SKY_FLAT'), ('STANDARD', 'STANDARD'), ('ARC', 'ARC'), ('LAMP_FLAT', 'LAMP_FLAT'), ('SPECTRUM', 'SPECTRUM'), ('REPEAT_SPECTRUM', 'REPEAT_SPECTRUM'), ('AUTO_FOCUS', 'AUTO_FOCUS'), ('TRIPLE', 'TRIPLE'), ('NRES_TEST', 'NRES_TEST'), ('NRES_SPECTRUM', 'NRES_SPECTRUM'), ('REPEAT_NRES_SPECTRUM', 'REPEAT_NRES_SPECTRUM'), ('NRES_EXPOSE', 'NRES_EXPOSE'), ('NRES_DARK', 'NRES_DARK'), ('NRES_BIAS', 'NRES_BIAS'), ('ENGINEERING', 'ENGINEERING'), ('SCRIPT', 'SCRIPT'), ('BIAS', 'BIAS'), ('DARK', 'DARK')], help_text='The type of exposures for the observations under this Configuration', max_length=50),
        ),
    ]
