# Generated by Django 2.2.4 on 2019-12-20 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestgroups', '0012_auto_20191123_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='repeat_duration',
            field=models.FloatField(blank=True, help_text='The requested duration for this configuration to be repeated within. Only applicable to REPEAT_* type configurations. Setting parameter fill_window to True will cause this value to automatically be filled in to the max possible given its visibility within the observing window.', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='configuration duration'),
        ),
        migrations.AlterField(
            model_name='instrumentconfig',
            name='exposure_count',
            field=models.PositiveIntegerField(help_text='The number of exposures to take. This field must be set to a value greater than 0.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
