# Generated by Django 2.2.12 on 2021-01-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestgroups', '0013_auto_20191220_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='state',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('WINDOW_EXPIRED', 'WINDOW_EXPIRED'), ('FAILURE_LIMIT_REACHED', 'FAILURE_LIMIT_REACHED'), ('CANCELED', 'CANCELED')], default='PENDING', help_text='Current state of this Request', max_length=40),
        ),
        migrations.AlterField(
            model_name='requestgroup',
            name='state',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('WINDOW_EXPIRED', 'WINDOW_EXPIRED'), ('FAILURE_LIMIT_REACHED', 'FAILURE_LIMIT_REACHED'), ('CANCELED', 'CANCELED')], default='PENDING', help_text='Current state of this RequestGroup', max_length=40),
        ),
    ]
