# Generated by Django 2.2.18 on 2021-05-25 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestgroups', '0015_auto_20210323_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentconfig',
            name='bin_x',
        ),
        migrations.RemoveField(
            model_name='instrumentconfig',
            name='bin_y',
        ),
    ]
