# Generated by Django 2.2.24 on 2021-09-01 21:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestgroups', '0016_auto_20210525_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='extra_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Extra Request parameters', verbose_name='extra parameters'),
        ),
    ]
