# Generated by Django 4.0.3 on 2022-03-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestgroups', '0017_request_extra_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisitionconfig',
            name='extra_params',
            field=models.JSONField(blank=True, default=dict, help_text='Extra AcquisitionConfig parameters', verbose_name='extra parameters'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='extra_params',
            field=models.JSONField(blank=True, default=dict, help_text='Extra Configuration parameters', verbose_name='extra parameters'),
        ),
        migrations.AlterField(
            model_name='constraints',
            name='extra_params',
            field=models.JSONField(blank=True, default=dict, help_text='Extra Constraints parameters', verbose_name='extra parameters'),
        ),
        migrations.AlterField(
            model_name='guidingconfig',
            name='extra_params',
            field=models.JSONField(blank=True, default=dict, help_text='Extra GuidingConfig parameters', verbose_name='extra parameters'),
        ),
        migrations.AlterField(
            model_name='guidingconfig',
            name='optical_elements',
            field=models.JSONField(blank=True, default=dict, help_text='Optical Element specification for this GuidingConfig'),
        ),
        migrations.AlterField(
            model_name='instrumentconfig',
            name='extra_params',
            field=models.JSONField(blank=True, default=dict, help_text='Extra InstrumentConfig parameters', verbose_name='extra parameters'),
        ),
        migrations.AlterField(
            model_name='instrumentconfig',
            name='optical_elements',
            field=models.JSONField(blank=True, default=dict, help_text='Specification of optical elements used for this InstrumentConfig'),
        ),
        migrations.AlterField(
            model_name='request',
            name='extra_params',
            field=models.JSONField(blank=True, default=dict, help_text='Extra Request parameters', verbose_name='extra parameters'),
        ),
        migrations.AlterField(
            model_name='target',
            name='extra_params',
            field=models.JSONField(blank=True, default=dict, help_text='Extra Target parameters', verbose_name='extra parameters'),
        ),
    ]
