# Generated by Django 4.0.2 on 2022-04-04 23:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestgroups', '0018_alter_acquisitionconfig_extra_params_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='configuration_repeats',
            field=models.PositiveIntegerField(default=1, help_text='The number of times to repeat the set of Configurations in this Request. This is normally used to nod between two or more separate Targets. This field must be set to a value greater than 0.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
