# Generated by Django 4.0.3 on 2022-05-06 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestgroups', '0019_request_configuration_repeats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraints',
            name='max_lunar_phase',
            field=models.FloatField(default=1.0, help_text='Maximum acceptable lunar phase fraction from 0.0 (new moon) to 1.0 (full moon)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='maximum lunar phase'),
        ),
    ]
