# Generated by Django 4.0.3 on 2022-06-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestgroups', '0020_alter_constraints_max_lunar_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='optimization_type',
            field=models.CharField(choices=[('TIME', 'TIME'), ('AIRMASS', 'AIRMASS')], default='TIME', help_text='Optimization emphasis, either TIME for as soon as possible, or AIRMASS for best airmass', max_length=40),
        ),
    ]
