# Generated by Django 4.0.3 on 2023-01-25 23:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestgroups', '0021_request_optimization_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraints',
            name='max_seeing',
            field=models.FloatField(blank=True, help_text='Maximum acceptable seeing', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='maximum seeing'),
        ),
    ]
