# Generated by Django 4.2.9 on 2024-05-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestgroups', '0023_alter_target_epochofperih'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestgroup',
            name='observation_type',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('RAPID_RESPONSE', 'RAPID_RESPONSE'), ('TIME_CRITICAL', 'TIME_CRITICAL'), ('DIRECT', 'DIRECT'), ('REAL_TIME', 'REAL_TIME')], help_text='The type of observations under this RequestGroup. Requests submitted with RAPID_RESPONSE bypass normal scheduling and are executed immediately. Requests submitted with TIME_CRITICAL are scheduled normally but with a high priority. These modes are only available if the Proposal was granted special time. More information is located <a href="https://lco.global/documentation/special-scheduling-modes/">here</a>.', max_length=40),
        ),
    ]
