# Generated by Django 4.2.23 on 2026-01-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestgroups', '0024_alter_requestgroup_observation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='suspend_until',
            field=models.DateTimeField(blank=True, help_text='Timestamp to suspend scheduling until for this Request. If it is > now, this request will not be considered for scheduling.', null=True),
        ),
        migrations.AlterField(
            model_name='requestgroup',
            name='state',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('WINDOW_EXPIRED', 'WINDOW_EXPIRED'), ('FAILURE_LIMIT_REACHED', 'FAILURE_LIMIT_REACHED'), ('CANCELED', 'CANCELED')], db_index=True, default='PENDING', help_text='Current state of this RequestGroup', max_length=40),
        ),
    ]
