# Generated by Django 4.2.23 on 2026-05-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestgroups', '0025_request_suspend_until_alter_requestgroup_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='type',
            field=models.CharField(choices=[('EXPOSE', 'EXPOSE'), ('REPEAT_EXPOSE', 'REPEAT_EXPOSE'), ('SKY_FLAT', 'SKY_FLAT'), ('SKY', 'SKY'), ('STANDARD', 'STANDARD'), ('ARC', 'ARC'), ('LAMP_FLAT', 'LAMP_FLAT'), ('SPECTRUM', 'SPECTRUM'), ('REPEAT_SPECTRUM', 'REPEAT_SPECTRUM'), ('AUTO_FOCUS', 'AUTO_FOCUS'), ('TRIPLE', 'TRIPLE'), ('NRES_TEST', 'NRES_TEST'), ('NRES_SPECTRUM', 'NRES_SPECTRUM'), ('REPEAT_NRES_SPECTRUM', 'REPEAT_NRES_SPECTRUM'), ('NRES_EXPOSE', 'NRES_EXPOSE'), ('NRES_DARK', 'NRES_DARK'), ('NRES_BIAS', 'NRES_BIAS'), ('ENGINEERING', 'ENGINEERING'), ('SCRIPT', 'SCRIPT'), ('BIAS', 'BIAS'), ('DARK', 'DARK')], help_text='The type of exposures for the observations under this Configuration', max_length=50),
        ),
    ]
