# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone/service-v1.json

apiVersion: v1
kind: Service
metadata:
  name: static
  labels:
    app.kubernetes.io/component: static
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: static
  ports:
    - name: static
      port: 80
      targetPort: static
