# Generated by Django 2.2.2 on 2019-08-15 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sciencecollaborationallocation',
            name='four_meter_alloc',
        ),
        migrations.RemoveField(
            model_name='sciencecollaborationallocation',
            name='one_meter_alloc',
        ),
        migrations.RemoveField(
            model_name='sciencecollaborationallocation',
            name='two_meter_alloc',
        ),
        migrations.CreateModel(
            name='CollaborationAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telescope_name', models.CharField(max_length=255)),
                ('allocation', models.FloatField(default=0)),
                ('sca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.ScienceCollaborationAllocation')),
            ],
        ),
    ]
