# Generated by Django 2.2.16 on 2021-02-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_auto_20190815_1942'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='timeallocation',
            constraint=models.UniqueConstraint(fields=('semester', 'proposal', 'instrument_type'), name='unique_proposal_timeallocation'),
        ),
    ]
