# Generated by Django 2.2.24 on 2021-06-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_auto_20210203_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('PI', 'Principal Investigator'), ('CI', 'Co-Investigator')], max_length=5),
        ),
        migrations.AlterField(
            model_name='proposalinvite',
            name='role',
            field=models.CharField(choices=[('PI', 'Principal Investigator'), ('CI', 'Co-Investigator')], max_length=5),
        ),
    ]
