# Generated by Django 2.2.23 on 2021-06-23 21:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_auto_20210617_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
