# Generated by Django 2.2.18 on 2021-06-04 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_auto_20210604_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeallocation',
            name='instrument_type',
        ),
    ]
