# Generated by Django 2.2.18 on 2021-06-04 21:55

from django.db import migrations


def forward(apps, schema_editor):
    # Fill in the instrument_types of TimeAllocations based on the current instrument_type field
    TimeAllocation = apps.get_model('proposals', 'TimeAllocation')
    for time_allocation in TimeAllocation.objects.all():
        time_allocation.instrument_types = [time_allocation.instrument_type]
        time_allocation.save()


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_auto_20210604_2154'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
