# Generated by Django 2.2.23 on 2021-06-24 01:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_proposal_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, help_text='List of strings tagging this proposal', size=None),
        ),
    ]
