# Generated by Django 2.2.18 on 2021-06-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_auto_20210604_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeallocation',
            name='instrument_type',
        ),
        migrations.AddConstraint(
            model_name='timeallocation',
            constraint=models.UniqueConstraint(fields=('semester', 'proposal', 'instrument_types'), name='unique_proposal_semester_instrument_type_ta'),
        ),
    ]
