# Generated by Django 4.0.4 on 2023-04-12 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_auto_20210708_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['-start', 'id']},
        ),
    ]
