# Generated by Django 4.2.9 on 2024-05-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_alter_semester_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeallocation',
            name='realtime_allocation',
            field=models.FloatField(default=0, help_text='Number of Realtime hours allocated'),
        ),
        migrations.AddField(
            model_name='timeallocation',
            name='realtime_time_used',
            field=models.FloatField(default=0, help_text='Number of Realtime hours used'),
        ),
    ]
