# Generated by Django 4.2.23 on 2026-01-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0010_timeallocation_realtime_allocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalinvite',
            name='time_limit',
            field=models.IntegerField(default=-1),
        ),
    ]
